# Generated by Django 4.2.5 on 2023-09-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_photos/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_photos', to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.photo'),
        ),
    ]
